use_frameworks!

platform :ios, '9.0'

target 'QYExternalAccessory_Example' do
  pod 'QYExternalAccessory', :path => '../'

  target 'QYExternalAccessory_Tests' do
    inherit! :search_paths

    
  end
end
